name: easybank

services:
  # Development Service: docker compose --profile dev up
  easybank-dev:
    build:
      context: .
      target: dev
    image: easybank-dev:1.0
    container_name: easybank-dev
    ports:
      - 3001:3001
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    profiles:
      - dev

  # Production Service: docker compose --profile prod build
  easybank-prod:
    build:
      context: .
      target: prod  
    image: easybank-prod:1.0
    container_name: easybank-prod
    mem_limit: 1024m # good practice for production
    ports:
      - 3002:80
    profiles:
      - prod
